### ISSUE TITLE
Map Controllers

### ISSUE THREAD

**Issue by paivaleonardo** [schellingb/dosbox-pure#13]
There is a way to insert a .map file into the game's .zip, as some automatic settings are buggy or not ideal.
Mortal Kombat Trilogy for example, does not map the block button.

**Comment by schellingb** [comment]
For this initial release there are only the built-in mappings available with no means to modify or add to them.  
The mappings come from a google sheet maintained by the keyb2joy.pad project which I don't even know if it is accepting public contributions. It also has no usage license (like GPL or creative commons) so all I could do is ask if I can use it and credit them in the program.

The keyb2joy.pad project data describes more button mappings than are used in DOSBox Pure. For example L3 is reserved for the on-screen-keyboard. Also the source data sometimes has more mappings that are bound to holding SELECT and pushing a stick into a direction. Even if DOSBox Pure supported these mappings, they couldn't be shown in RetroArch's Controls screen which defeats the purpose.

Sorry for the non-answer but I don't have anything planned yet for how to proceed from here. Maybe I can make a simple website where one can define a mapping and select a game from a list and it spits out some code that could somehow be imported?

**Comment by Darknior** [comment]
Thanks, it's a good idea but maybe complicated.
Is there a way to identify an EXE file ? With CRC32 for exemple ?
And use it to build a database to automatically configure games. With a big XML file on git that contributors can help to improve.
Like they do on console emulators, Saturn Playstation etc ... for some controllers, hacks and cheats ... Widescreen hack etc ...
Less work for you, and users will must help to build it. And easier to use for every one because included and auto.
Just an idea ... thanks a lot for your fantastic work :)

**Comment by schellingb** [comment]
Absolutely. I'd even be interested in starting such a project. But as I said the current mapping database is owned by the people who wrote it so I can't just copy that. And starting over from scratch would be a waste (and an insane amount of work).

Not that things can't be talked about, Jemy and Bigjim who made the mappings are cool and I talked to them for a bit while building this thing. Let's see where we can go from here. I think this proof-of-concept is fairly successful. It's the best I could do for this year. I think the way controls can be browsed in RetroArch works out surprisingly well, it's even some form of built-in help.

One idea I had was that some games like DOOM need a full range of keys to select weapons. Instead of mapping 7 different buttons or button combination, the range could be defined and 2 buttons could be used to toggle through them. Of course that would still toggle through weapons that the player hasn't picked up but it seems better than nothing. We also could go a step further and use the cheat search tool to find the memory locations of the weapons and make it actually intelligent. That seems a bit complex though, but certainly possible :-)

**Comment by Darknior** [comment]
You really have some great ideas !!!!
For sure it's bad to stol work of others ... but maybe if you ask them, they can be interested to help to add there work on your Dosbox  with database system to help more and more users ... with time libretro emulators are the future. Easy to use and compile on any devices :) 
For sure switch weapons with two keys like on console port is the best way, but like you write, it will be ask for CHEAT code to make it perfect to use.

**Comment by paivaleonardo** [comment]
Yes, I already knew this project, and even used it, it is integrated with the Exodos project, which I use as source for games in .zip.
The way is to use keyarch mapping, even native to Retroarch, and save those that are not good by game. I just wanted to know if your Core generated any file that was editable or that recognized a .map directly inside the games folder. Thanks!
