### ISSUE TITLE
M. Flight Simulator 5.1 - "Out of Memory" error, can't disable EMS and upping memsize at the same time.

### ISSUE THREAD

**Issue by demodanza** [schellingb/dosbox-pure#139]
Hi!
The game Microsoft Flight Simulator 5.1 crashes with the error message "Out of Memory" after the title screen. The same game works on dosbox, but with the following specific settings that can't be set on the core's menu:

memsize=128
xms=true
ems=false

With how the core options are set up right now, memsize only goes up to 64, and xms/ems can only be disabled together while limiting the memsize when doing so. Ideally XMS, EMS and Memsize should be three separate options, with a toggle for the first two and the option to raise the memory a little higher for the latter.

Thanks for the continued development, I hope this can be fixed somehow.

**Comment by ToniBC** [comment]
I have tried the Microsoft Flight Simulator game (v5.1) with the default configuration and the game starts, inside it is configured as SVGA 640x400 and everything seems to work, everything moves and that, although it does not take off, but I can move the levers.

**Comment by demodanza** [comment]
That's really weird... I just tested resetting the core's options to default and even changed the game's setting to the lowest and still got the error after the title screen. I'm attaching a video of the process.

https://user-images.githubusercontent.com/47835860/117184016-3e84d080-ada6-11eb-98de-6f64303375ec.mp4

As I understand, the program itself it's abandonware, so I can upload the zip if needed.

**Comment by ToniBC** [comment]
I use the ExoDOS version and by setting the Setup, selecting the maximum, Pentium and VGA, the game starts without problems. From what I see there, it may be that you do not have it installed, that error is because you are trying to install it and I think that it is not possible with zip files or some problem.

That menu that you put is only for the initial configuration, then it starts with another .bat. If you already have it installed and functional in normal Dosbox, you just have to zip it and run it.

By the way, the version I use is on CD.

**Comment by demodanza** [comment]
It works! Thanks a lot for the directions, I clearly had badly set up my copy, but now it works. Thanks for your work and your patience. Have a great weekend!
