### ISSUE TITLE
Unable to parse zip files of greater than 2 GB

### ISSUE THREAD

**Issue by soultrain** [schellingb/dosbox-pure#15]
Multi-CD games which are in a single .zip file can't be loaded if the zip file is over 2 GB. Was able to test by removing cd images from the zip files and reloading, which causes the data to be seen. I know it doesn't affect a lot of games but there are definitely games in the CD era with many cds.

Wing Commander 3 as a test, before removing a CD image:
![image](https://user-images.githubusercontent.com/4437934/102918053-4295fe80-4454-11eb-86ec-f62061c473df.png)

Wing Commander 3 as a test, after removing a CD image:
![image](https://user-images.githubusercontent.com/4437934/102918202-7d983200-4454-11eb-91b8-9d579d375421.png)

**Comment by schellingb** [comment]
Yes, the limit is 4GB of uncompressed data because Zip64 isn't supported. You can check by opening the file in 7zip and clicking the info button, and if it shows `Characteristics: Zip64` it's sadly not compatible for now.

I think I thought that no DOS games are that big, but of course they are!

Zip64 shouldn't be too hard to implement if I remember correctly. I've been looking for an excuse to do so for a few years actually :-) I'll look into it first when it comes to new additions.

**Comment by soultrain** [comment]
You got it, this is what the main zip looks like:
![image](https://user-images.githubusercontent.com/4437934/102920094-09f82400-4458-11eb-8d66-d0ff08eb4f6a.png)

**Comment by soultrain** [comment]
It's definitely a 2GB limit though, I'm trying other games and walking up to that, which work fine. once you pass that in a zip, it fails.

**Comment by schellingb** [comment]
Huh, ok, let me take a closer look then. Thanks for confirming!!

**Comment by schellingb** [comment]
@soultrain Please check the new 0.2 release it should now support ZIP files larger than 2GB (up to 4GB).

**Comment by soultrain** [comment]
That fixed it! Thank you!

**Comment by shakeyourbunny** [comment]
4 GB won't cut it.

There are DOS games which have more than 4 GB data :)

**Comment by schellingb** [comment]
@shakeyourbunny I'm very well aware of that. But the Zip64 support which is needed for that will take more than just a few hours.
