### ISSUE TITLE
Make Available Analog Stick Axises In Custom Keybinds Option

### ISSUE THREAD

**Issue by matercir** [schellingb/dosbox-pure#164]
They currently are not available when in regular custom keybind mode, it would be nice to have them as inputs for digital keys.

**Comment by PoloniumRain** [comment]
I was going to post this. It's a real problem with some games.

Here's one example: Hexen
The automatic key mapping doesn't work with this game, so then i try to use 'Custom Keyboard Bindings' as this actually lists **every** single keyboard key (unlike the other Device Type options). But this Custom option doesn't let me map keys to the analog stick directions.

So far i've come across several games that have this problem and i can't use a controller with them because of it. It might be possible to go in each individual games setup, then configure the controls to the keys that DBP actually lists in other Device Type options, but that's time consuming and probably wont be possible for every game.

**Comment by schellingb** [comment]
This is a limitation of RetroArch and not something this core can easily fix or work around. Opening an issue on the RetroArch project would be a good idea I think. As far as I understand RetroArch internals, this shouldn't be too hard to add.

I originally planned to have a means to create and modify the automatic controller mappings which would make all kinds of customization possible. Until that (rather big) feature exists, unfortunately there's not much that can be done.

On PC platforms tools like [Antimicro](https://github.com/AntiMicro/antimicro) can be used to map controller to keyboard keys which makes everything possible, though I'm aware how cumbersome this "solution" is.

If you think  another libretro core has a good solution to this problem, I'd look at it.

**Comment by matercir** [comment]
> This is a limitation of RetroArch and not something this core can easily fix or work around. Opening an issue on the RetroArch project would be a good idea I think. As far as I understand RetroArch internals, this shouldn't be too hard to add.
> 
> I originally planned to have a means to create and modify the automatic controller mappings which would make all kinds of customization possible. Until that (rather big) feature exists, unfortunately there's not much that can be done.
> 
> On PC platforms tools like [Antimicro](https://github.com/AntiMicro/antimicro) can be used to map controller to keyboard keys which makes everything possible, though I'm aware how cumbersome this "solution" is.
> 
> If you think another libretro core has a good solution to this problem, I'd look at it.

P-UAE allows mapping keyboard keys to analog sticks, but I'm not sure how much removed from dos that is.

**Comment by schellingb** [comment]
Yeah PUAE does the (in my opinion) ugly workaround of adding core options for every Retro Pad input with 100s of options. On top of this it also has custom keyboard just like DOSBox Pure does (with the same limitations of not supporting analog stick directions).

In a sense libretro has too many options I guess. If the custom keyboard feature didn't exist it would be easier. But because it exists, I think it would be much better to improve RetroArch in that regard than add these custom workarounds to each core. I guess computer cores are just not popular enough to have more people look into improving things like this...

I have contributed to RetroArch before, maybe I'll take a stab at this. No promises :-)

**Comment by matercir** [comment]
> Yeah PUAE does the (in my opinion) ugly workaround of adding core options for every Retro Pad input with 100s of options. On top of this it also has custom keyboard just like DOSBox Pure does (with the same limitations of not supporting analog stick directions).
> 
> In a sense libretro has too many features I guess. If the custom keyboard feature didn't exist it would be ~easier~ a no-brainer . But because it exists, I think it would be much better to improve RetroArch in that regard than add these custom workarounds to each core. I guess computer cores are just not popular enough to have more people look into improving things like this...
> 
> I have contributed to RetroArch before, maybe I'll take a stab at this. No promises :-)

Yeah i'm sorry, my understanding of the inner workings of libretro are very poor. So I don't know how one thing is implemented or not in terms of a core per core basis.

I wouldn't mind starting an issue on retroarch asking for a feature that would help with this, but I'm not 100% sure what I'm asking :(

**Comment by schellingb** [comment]
So, I think I was able to modify RetroArch to accommodate this.
With my changes, when setting the Device Type of a controller port to "Custom Keyboard Bindings", the list of possible key assignments now has 8 more entries at the bottom (4 directions for the 2 analog sticks) which can be assigned just like any of the pad buttons.

@matercir Just to make sure, does this match your request?

I'll clean it up a bit and send a pull request towards the RetroArch repo, then maybe after someone there can check it out it can be integrated into the next version.

**Comment by matercir** [comment]
It does indeed,  I'll close the issue, tyvm :)
