### ISSUE TITLE
Slight Drift With Onscreen Keyboard

### ISSUE THREAD

**Issue by baltimoresports** [schellingb/dosbox-pure#24]
I am experiencing a slight drift when using the onscreen keyboard. No other issues with drifting.

Version: 0.2
Gamepad: Xbox One
RetroArch: 1.9.0

**Comment by schellingb** [comment]
Have you tried other (true) analog stick features in DOSBox Pure? For example, setting the control device type to 'Mouse with Left Analog Stick' and playing a game with mouse support?

How about in other cores in RetroArch that have full analog stick support?

For now I can only suggest to set the RetroArch option Input -> Analog Deadzone to 0.1 or 0.2.

**Comment by baltimoresports** [comment]
Full disclosure, this might be hardware. Tried a second controller and it seems fine. To answer you questions:

- Everything in this core, except keyboard works. Other cores work. Calibration tests in Windows show no drift. 
- Input was set to 0.0

If no more issues on the other controller, we can probably bag this one and close it. Thank you. Really looking forward to this project! Great job so far.

**Comment by mrmatteastwood** [comment]
FWIW, I had the same issue when I first installed DOSBox Pure. I was a bit surprised that the drift only occurred on the Pure keyboard overlay, and not e.g. in ScummVM games. That said, I would agree it's a hardware issue and it's easily fixed by going to RetroArch's Settings > Input > Analog Deadzone and nudging that up just a bit. For me, 0.3 was enough.

**Comment by baltimoresports** [comment]
- Upgraded to 0.3. 
- Upgraded Xbox firmware. 
- Still drifting, but seems to drift less.
- Deadzone to 0.1 seems to fixed it for me.
