### ISSUE TITLE
How to disable auto centering in Quake?

### ISSUE THREAD

**Issue by Tasosgemah** [schellingb/dosbox-pure#244]
Quake runs great on the core and the controls are also good with a dual analog scheme.

But the issue i have is that every time i move forward/backward, the camera auto centers. So, for instance, i can't move while looking up or down because when i try that, the camera always tries to center.

How do i disable that behavior?

**Comment by arrowd** [comment]
IIRC, it is also the same for real DOS. It is just game specifics.

**Comment by PoloniumRain** [comment]
This happens because Quake doesn't have mouse look enabled by default, so it auto centres the camera when you move. You can enable mouse look by typing **+mlook** in the console and this will fix the camera issue, but the problem with this method is that it doesn't save it, so you have to type this every time you play.

So do this to permanently save the mouse look setting: 

1. Go to the **ID1** folder inside the game folder.
2. Create a file called **AUTOEXEC.CFG** and open it in any text editor.
3. Paste the following:
_//add crosshair
crosshair "1"
//mouse look up and down
+mlook
//disable vertical auto aim
sv_aim 1_

5. Save it. 

There's some other useful features there like enabling a crosshair, but If you don't want to use them, just add **+mlook**.

**Comment by Tasosgemah** [comment]
> This happens because Quake doesn't have mouse look enabled by default, so it auto centres the camera when you move. You can enable mouse look by typing **+mlook** in the console and this will fix the camera issue, but the problem with this method is that it doesn't save it, so you have to type this every time you play.
> 
> So do this to permanently save the mouse look setting:
> 
>     1. Go to the **ID1** folder inside the game folder.
> 
>     2. Create a file called **AUTOEXEC.CFG** and open it in any text editor.
> 
>     3. Paste the following:
>        _//add crosshair
>        crosshair "1"
>        //mouse look up and down
>        +mlook
>        //disable vertical auto aim
>        sv_aim 1_
> 
>     4. Save it.
> 
> 
> There's some other useful features there like enabling a crosshair, but If you don't want to use them, just add **+mlook**.

Thanks, it works :)

Closing it since that's not really a DosBox Pure issue anyway.
