### ISSUE TITLE
On-Screen keyboard no longer works when using custom keybindings

### ISSUE THREAD

**Issue by mrmatteastwood** [schellingb/dosbox-pure#25]
**Steps to Reproduce:**
1. Start RA with DOSBox Pure core in Linux Mint or Windows 10
2. Run any DOS game using the Pure core
3. In Quick Menu > Controls > Port 1 Controls, select "Custom Keyboard Bindings" and create a custom key mapping profile
4. In-game, press down left thumb to bring up on-screen keyboard

**Expected Results**
The on-screen keyboard overlay should appear when pressing down the left thumb in-game, even when a custom key binding profile is set.

**Current Results**
The on-screen keyboard does appear when pressing down the left thumb stick while using key mapping profiles like the automatically detected key mappings, generic key mappings & co., but not when using a custom key mapping profile.

**Notes**
- Issue first encountered in DOSBox Pure version 0.3.
- This might be related to the fix implemented for issue #14, "Controller jumps 2 lines in start menu" (https://github.com/schellingb/dosbox-pure/issues/14)
- I noticed that more button mapping options are available when selecting e.g. Generic Keyboard Bindings than in Custom Bindings. For instance, in "Generic", one can map keys to the left and right trigger axes, which is not possible in Custom.

**Comment by schellingb** [comment]
Now we're getting into the thick of it :-)
So yeah this is related to the "fix" of #14 which limits the "non-DOS" input handling to just keyboard and mouse if the first controller port has been set to "Custom Keyboard Bindings" or "Disabled".

Now that I think about it, for the on-screen keyboard, I think we can roll that back. And also completely disable keyboard control of the on-screen keyboard (for now arrow keys can move the cursor etc.). With the keyboard disabled, there won't be any double-input even if "Custom Keyboard Bindings" is used.

For the start menu things get a bit complicated. We don't know if the "Custom Keyboard Bindings" are set to the arrow keys. If they are set to arrow keys, there could be double-input like we noticed before. If they are not set to the arrow keys, with the fix, navigation could be impossible.

So maybe instead of disabling the joypad input completely when set to "Custom Keyboard Bindings", we just detect double-input in software. Let's say if someone presses a direction twice in a 5 millisecond window, ignore the second one. Should be no downside to that I think.

**Comment by mrmatteastwood** [comment]
Hey @schellingb, interesting! I'm not sure I fully understand what your fix for #14 entailed. So, do I understand correctly that there are technically two "layers" of button mapping:

First is on the umbrella "RetroArch" level, it includes pre-defined standard mappings like keyboard arrow keys to controller d-pad, user-set RA hotkeys like fast-forward, and the DBPure-specific hotkey for the on-screen keyboard (left trigger button).

The second is on the core-specific "DOS" level, and it involves whatever a user sets in custom key mappings.

Correct?

Is it also then correct that you disabled the first, "RetroArch" layer of button mapping completely for custom key bindings, which kinda meant trowing out a couple babies with the bathwater? And you mean that you could selectively roll back that deactivation, like just for the on-screen keyboard hotkey?

I see that disabling the first layer would put the user in the position that they'd have to really take care of all mapping themselves, otherwise they might be unable to navigate. I think that's a risk we could take, personally. A user will (have to) understand that if they don't bind certain keys, they can't expect the associated functions to work anyway.

I like the solution with the 5-millisecond window.

_On another note, if my assumption about the two layers of input assignment is correct, do you have a full list of which gamepad buttons do what by default in DOSBox Pure? I'm sure you do and I probably overlooked or forgot I saw it._

**Comment by schellingb** [comment]
Please try again with the [latest release](../releases/latest).

**Comment by mrmatteastwood** [comment]
Yes! Everything works perfectly, at least on my end. Awesome :-)
