### ISSUE TITLE
Folders with certain bracket arrangements no longer work within zip files

### ISSUE THREAD

**Issue by n1ghttrap** [schellingb/dosbox-pure#255]
Expected and previous behavior:  a zip file with the folder "DOOM v1.666 [SWR] (1994)(id Software, Inc.) [Action]" inside it will display that folder's contents as the root with no parent directories before it and executables will work fine within it.  This is how it was with a core I had saved from 3/20/22 (0.26) at least. 

In the most recent core (0.9.1) I get a truncated directory and nothing loads from it, giving me the following for each:
![DOOM v1 666  SWR  (1994)(id Software, Inc )  Action -220503-221331](https://user-images.githubusercontent.com/30274474/166618703-ac6f2216-e52d-4438-a943-06a4c0669d82.png)
![DOOM v1 666  SWR  (1994)(id Software, Inc )  Action -220503-221347](https://user-images.githubusercontent.com/30274474/166618714-19cd4fd6-d879-426c-b734-aaf2a69a8d3c.png)
:

This is exclusive to the new core as the old .26 core doesn't have this in the latest nightly Windows x86_64 Retroarch build.

**Comment by n1ghttrap** [comment]
Looking closer it's something to do with the end of the folder and the brackets. 
Working:
DOOM v1.666 [SWR] (1994)(id Software, Inc.)  
DOOM v1.666 [SWR] (1994)(id Software, Inc.) Action]
Not working:
DOOM v1.666 [SWR] (1994)(id Software, Inc.) [
DOOM v1.666 [SWR] (1994)(id Software, Inc.) [Action
DOOM v1.666 [SWR] (1994)(id Software, Inc.) [Action]

Doing some other tests:
Working:
asdf
asdf[asdf
asdf[asdf[asdf (any amount of brackets so long as it doesn't end with one)
Not working
asdf[
asdf[asdf[

So it's really hard to recreate without all the dots and parenthesis and dashes in most of my other zips, but something's screwy with the brackets.

**Comment by schellingb** [comment]
When loading ZIP files, filenames that don't fit into the DOS 8.3 filename format the names get shortened to the first 4 characters, the last 4 characters, and up to 3 characters of the extension. When implementing that I contemplated using the Windows 95 long-filename style (which adds ~# where # is a number based on the internal ordering) but I realized that while filenames like EXE files from DOS obviously fit into the DOS format, CD images like ISOs frequently have long filenames and often have some vital information at the end so one can know which CD number to mount in the start menu or the disc menu.

Anyway, while shorting/filtering filenames in the ZIP file, the core left some special characters like (`"*,/:;<=>?[\]|`) in the names as is even though they are invalid on the DOS file system. I fixed that now and these characters get converted to a minus `-` and make these cases work. The problem was introduced for you by the recent "Don't enter solo root directory when mounting ZIP files" change but the inherent issue of not filtering out the bad characters was there all along. Thanks for reporting.

**Comment by n1ghttrap** [comment]
Thank you.  When will the fixed version be available to use?

**Comment by n1ghttrap** [comment]
Tested a number of my zips with folders in them, brackets and many special chars each, and it loads executables fine now.  Thank you.

**Comment by schellingb** [comment]
Thanks for confirming! Awesome!
