### ISSUE TITLE
We should be able to select ANY keyboard keys in all selected devices even if its gamepad

### ISSUE THREAD

**Issue by ZeroAlvein** [schellingb/dosbox-pure#260]
Look i appreciate that option to fake using actual gamepad exist even so i don't use it
I need to go for custom keyboard and mouse controls resigning from that default gamepad bindings or usage of that emulated gamepad at all
Why?

Because in every single game you gonna play, if you want to control it with your physical controller you will most likely also want to bind some buttons on your physical controller to keyboard so like you can hit escape with idk L1 or go to help which is usually done by pressing F1 which you could bind to select on your controller
And now you simply can't if device selected is something else than custom keyboard and mouse
I mean some devices have some keys but not all
It's cool to have some games use auto config binds but when i want to add idk F10 there simply is no option for that
I need to go and change device type to custom keyboard and mouse and do binds from scratch

IDK if it's impossible or is it oversight but for sure it's frustrating not being able to do so

**Comment by schellingb** [comment]
The core exhausts all options offered by the libretro API. It offers the option to have up to 24 functions bindable to any part of the RetroPad. As an alternative it offers the option to have any keyboard key bindable to any part of the RetroPad but that removes the ability for the core to offer any bindable functions that aren't keyboard keys.

Anyway, long story short, it sounds to me that the [Gamepad mapper](../#gamepad-mapper) would solve any of the presented issues at hand. Does it not?

By the way, this is free software I've written in my spare time, I'd appreciate if the feedback were written, you know, a tiny bit less rude. Also there are a bunch of existing issues that are extremely similar to yours and I've attached a note to all of them explaining about the recently added gamepad mapper feature. The feature is also mentioned in the recent [release notes](../releases). For feedback on the gamepad mapper, please add it to the existing issue #57, having it all in one place helps immensely.

**Comment by ZeroAlvein** [comment]
IF you think that was rude you didn't get me at all
I was just pointing out it makes no sense
It's like having forks in kitchen but spoons in bathroom like how much sense does it make?
So do not feel like im lecturing you about something i have no idea how it works in the first place

And gamepad mapper should not be solution here you see that's why i know you didn't get me at all
Not all of us have L3 on our gamepads (actually i do on all) heck some don't even have L/R 2 or even 1 also
So like not everyone can afford to sacrifice 1 button to have special functions
Anyway
When you go to change button mapping what you expect?
Well to map any key to any button and not just some
All ppl that comes to retroarch discord for help with dosbox controls have same exact issue and i simply tell them to switch to custom keyboard and mouse binds
So by default they don't use that auto generated gamepad mappings since they can't set many keyboard keys they would actually use/need to control WHOLE game with just controller

BUUUUUT now since i understand that it's kinda technical limitation of RA and not simple choice to separate keyboard input from gamepad input i gonna point all that ppl to gamepad mapper like you mention

But what i can suggest and would be cool to have option to use and be able to set combo keys to bring up that gamepad mapper overlay (actually i think it's simply virtual keyboard overlay)

Also i have no idea what you mean by "add it to existing issue"? Do you mean like i copy that whole text from my issue and just paste it in the #57  one? or i need to click something?
I will gladly do that but i kinda lack of knowledge how to do stuff on GH

If you feel like im rude to you or that i want to say you did something wrong then im sad cause you really get me wrong and i have no problem saying i am sorry and apologize to you since that's not what i was trying to express

You actually made many ppl being able to experience their childhood nostalgia in many different ways for me it's on smartphone
I have no idea how you can even think any1 would be disrespectful to you even so if they don't like something about your work
So in their name and especially speaking for myself Thank You for your work ;)

**Comment by schellingb** [comment]
Having the first word in the feedback be "Look" feels rude to me.
Having a whole line dedicated to "why?" feels rude to me.
The tone of the message feels rude to me.
You mentioned being frustrated with the limitations, and that frustration clearly comes through in the way the issue report is written. But we can move past that, after all I'm still here taking the time to reply. The second message was already much better :-)

Anyway, different cores handle things differently in this regard. The other DOSBox cores have even less presets and nothing like automapping, on-screen-keyboard or gamepad mapper. The VICE core (Commodore computer emulator) has one way of dealing with this by having 20 distinct core options with hundreds of selectable things. I don't like that at all. If you think another core has a better approach I'm open to hear suggestions. Personally I think we have a good balance between complexity and usability which is important to me.

Your original message doesn't contain any feedback or suggestion regarding the gamepad mapper so it doesn't belong to #57 as is. Ideally instead of creating this new issue, you could have posted a reply to #57 saying something like "It would be useful to have the option to use a button combination to open the on-screen keyboard and thus the gamepad mapper because some users might not have L3 or don't want to dedicate a button to it" and be done. I think that is a decent suggestion for a further enhancement.

Also, if you're using it on a phone, you could add your voice to #231, I always thought that was the biggest shortcoming of this core for phones, but so far only one person mentioned it... Maybe most people skip mouse based games when playing on the phone?

**Comment by ZeroAlvein** [comment]
Schellingb i really can't have any control over what you consider rude i can't also take any responsibility for that
I simply started with "LOOK" so no1 could say im here just to betch about feature i think should be implemented and that does not exist and someone did a poor job not thinking it trough.
And when you read tone out of text instead of simply asking it's kinda equivalent of believing politicians are nice to you because they care for your "good" well i prefer to keep my good for myself

Many cores have different options some are betters some are worse
But it's like food i love potatoes someone can hate them so nothing here to argue about
But i think i have few ideas you can consider and gonna post them in #57 actually regarding that virtual keyboard
 
About phones gaming that is little bit complicated topic which i think can be narrowed down to 2 things
 
 1. Not everyone own a controller so there is that and many of us use overlays with virtual pad which are terrible for accurate controls for something like doom or jazz jackrabbit
 2. Adding single file to playlist does not exist but that is kinda RA lack of feature
 I don't zip my dos games and when i want to add executable i either need to specify in import content to add exe or bat file extensions
 But when there are multiple files i need to go back to my playlist and remove all other files like setup and dos4gw and other crap like that
 NOT WORTH YOUR EFFORT
 Especially when you have many games
 
 But for me well
![a](https://user-images.githubusercontent.com/99673761/168887785-cd20e61a-e007-473f-9694-e4246d28384b.jpg)

Yes this is windows 3.1 inside dosbox pure inside retroarch on android phone and im playing Zombie Wars on it and runs perfectly fine
I also tested Fury 3 which is another windows 3.1 game and also works just fine

I did read #231 and i think i have solution for that also and i gonna contribute what i can

**Comment by schellingb** [comment]
We're done here.
