### ISSUE TITLE
After Burner II crashes RetroArch

### ISSUE THREAD

**Issue by Tasosgemah** [schellingb/dosbox-pure#29]
When i load this game with version 0.3 of the core RetroArch crashes.

It loads with an older, regular DOSBOX core.

I'm using roms from the eXoDOS pack.

**Comment by schellingb** [comment]
Thank you so much for catching this!
It seems all games that have a button mapping that maps a single button to 3 keys we're affected by this problem:

- After Burner II
- Caddiehack
- Cheon'gong Cheon'gi
- Congo Bongo
- Devil Land
- Double Dragon III - The Sacred Stones
- Downhill Challenge
- Dracula's Shadow
- Dreamworld Adventure
- Hello Mr. President
- Islands of Danger!
- Michel Futbol Master + Super Skills
- NightHunter
- Outer Ridge
- PChallenge
- Rise of the Robots
- Rusty
- Skull & Crossbones
- Starduel
- Street Racer
- Stryx
- Super Apocalypse Warriors
- SuperSki

Will be fixed in the next release. Thanks again!

**Comment by Tasosgemah** [comment]
Hey my pleasure. I'm trying a lot of games and the core is surprisingly issue free with most that i throw at it. So if it helps i'll report any issues i catch.

**Comment by schellingb** [comment]
Ah, Congo Bongo seems to be fine, as the 3 key mapping isn't used. Rise of the Robots ends up not crashing but the mapping is broken. I'm not doing anything manually, just fixing the converter script that handles these :-)

**Comment by schellingb** [comment]
Ok, fixed mappings are in 0.4, please try again, thanks!

**Comment by Tasosgemah** [comment]
Yeah, it works now, gg
