### ISSUE TITLE
[Feature Request] Selection of format and size of D drive at 1st creation

### ISSUE THREAD

**Issue by RaouleMenard** [schellingb/dosbox-pure#296]
Hi, here's a simplified version of my request.

Currently, when selecting a CD then an installed OS, the 1GB D drive is created.

When this is the first time, please allow to select the format / size of this drive such as "1GB FAT, 2GB FAT32" etc. You could use the same type of menu as the installed OS selection.

Sorry again, though I think many users will face the 1GB limit so this is really important. Thanks!

**Comment by schellingb** [comment]
Not sure I can make a selection and remember the option or anything like that.

How about a core option then?

The only thing that could be confusing is that when you start using this with 1GB space and put some stuff on various D: drives and then switch to more free space the changes will seemingly vanish because it will start over with a "new" D: drive.

**Comment by RaouleMenard** [comment]
A core option would work, or even a hidden config option that you can only set in the .CFG file - if you're afraid some users would get confused.

I'll only have to set it once to 2GB - as I only plan on using Windows 98 SE and will never switch to 1GB ever.

**Comment by PoloniumRain** [comment]
Core options for 1/2/4GB would be good to have. I don't know of any game/software from that era that uses more than 2GB although i'm sure someone will somehow need it... (possibly myself).

And i don't know if this will be possible, but if you were to implement FAT32 support for OS installation, it would be a nice feature if DOSBox-Pure detected if the loaded .IMG image file is FAT32 and then automatically uses something very large like 4GB FAT32 for the D: drive. If a FAT16 image file is loaded it could use 2GB FAT16 for the D: drive. These larger default sizes would make more sense because of the way the D: drive .SAV files work, as they only take up the same amount of space as the installed game/software, so physical storage space concerns aren't so much of an issue here like they are with .IMG files. **IF** it could be done this way most users will likely never have to mess around with any settings.

> The only thing that could be confusing is that when you start using this with 1GB space and put some stuff on various D: drives and then switch to more free space the changes will seemingly vanish because it will start over with a "new" D: drive.

This could be mentioned in the description text underneath the core option?

**Comment by RaouleMenard** [comment]
Hi @schellingb and thanks a lot for the fix! Unfortunately I'm not able to test as it's still not live on the nightly builds.

As soon as it is I'll test it and report!
