### ISSUE TITLE
Pretty much all the games that i tried  freezes randomly on DOSBox pure

### ISSUE THREAD

**Issue by mkm007** [schellingb/dosbox-pure#317]
Hi to all, DOSBox pure really good emulator I like and respect the handwork that DOSBox pure team put on their product but unfortunately most of the games that I tried like The need for speed 1 (DOS), Duke Nukem 3D . terminator Skynet and future shock, blood, etc. always randomly freezes on gameplay for few seconds and the fun fact was DOSBox SVN don't show any sorta freezes for the games that I tried .And also i noticed  this issue is something to do with 7zip compression  is there any fix that you guys can offer.Kindly let me know thank you keep the good work

**Comment by TradeDraft** [comment]
Tried just making the Zipped Files .zip Files?

**Comment by mkm007** [comment]
> Tried just making the Zipped Files .zip Files?

it's actually a zip file but i have 7zip to use this file I mean i consider there is no much difference it gonna make either I use 7zip or win zip or even win rar at the end this are compressed formats which may freeze the game in one point or another

**Comment by PoloniumRain** [comment]
What OS are you using? What device? What RetroArch and DOSBox-Pure versions?

You could try resetting all the DOSBox-Pure options to the default settings by going to RetroArch\config\DOSBox-pure and deleting the `DOSBox-pure.opt` file. It will be recreated the next time you run the core.

Or try downloading the latest [RA nightly](https://buildbot.libretro.com/nightly/) portable version (.7z file). Just extract it and download the DBP core. This way it's also easy to try it out on different hard drives/SSD's, because a faulty or extremely slow drive could be causing your problem.

But i always use 7zip to create .ZIP files and i've never had any problems with hundreds of games. Do you use the 'Deflate' compression method? That's pretty much all that's needed and it's the default setting anyway. Below are my settings...

![image](https://user-images.githubusercontent.com/50634894/180416678-9d497708-d273-47d7-ac76-871ca35e1aaf.png)

And also by default, right clicking on a folder/file and going to 7zip > add to <<FileName>FileName>.zip will also use the deflate method.

**Comment by mkm007** [comment]
> 
hi thank you for the reply and here's my specs I'm using a dell laptop with specs of 16gb ddr4 dual channel ram, nvidia gtx 1050 gpu. i5 7300hq(2.50 ghz) 4 core and 4 thread processor with 256gb nvme ssd and 1tb of internal hdd windows 10 genuine home version with all latest updates necessary and i'm using iso file to install the game which automatically created C drive with installed game as zip format so i'm not manually compressing anything it's just dos box pure itself create the files within the zip format as  C drive and i tested this game by changing their location first i used my internal hard drive space to install this games with retroarch saves directory and it cause random freeze and then i installed this games on my inbuilt nvme ssd too but with random freeze in the apps as always....

**Comment by PoloniumRain** [comment]
It should certainly work on that hardware. Try doing things this way.... Download the same games from ExoDOS - You'll find ExoDOS with a quick search on any search engine. It's a massive collection of DOS games which are already pre-installed within .ZIP files. 

Then all you have to do is:
Open RetroArch > Main Menu > Load Content > find the game ZIP file and load it with the DOSBox-Pure core.

See if that works.

And to make sure you're using the latest RetroArch and DOSBox-Pure versions: 
Go to Main Menu > Load Core > DOSBox-Pure, then in the bottom left corner it will say both the RA and DBP version numbers. 
These are the latest versions...
![image](https://user-images.githubusercontent.com/50634894/180466964-0783c91f-a41c-4dfd-99d1-2584b43e3135.png)

**Comment by mkm007** [comment]
thank you so much I definitely give a try and I will let you know the results....

**Comment by mkm007** [comment]
> It should certainly work on that hardware. Try doing things this way.... Download the same games from ExoDOS - You'll find ExoDOS with a quick search on any search engine. It's a massive collection of DOS games which are already pre-installed within .ZIP files.
> 
> Then all you have to do is: Open RetroArch > Main Menu > Load Content > find the game ZIP file and load it with the DOSBox-Pure core.
> 
> See if that works.
> 
> And to make sure you're using the latest RetroArch and DOSBox-Pure versions: Go to Main Menu > Load Core > DOSBox-Pure, then in the bottom left corner it will say both the RA and DBP version numbers. These are the latest versions... ![image](https://user-images.githubusercontent.com/50634894/180466964-0783c91f-a41c-4dfd-99d1-2584b43e3135.png)

hi its finally working  and yes i tested some games with exodos zipped version  and they are working properly but something wrong with 3dfx implementation because shadow warrior and blood 3dfx version not working properly

**Comment by PoloniumRain** [comment]
Glad you got it working!

Both Blood and Shadow Warrior have problems with 3dfx but it's probably not because of DOSBox-Pure. Blood only ever received an alpha patch for 3dfx support, which is buggy and hard to get working, and Shadow Warrior can just show a black screen. It's like this on real hardware. You're not missing anything though... Build engine games look worse with 3dfx and they're still not true 3D, so all 3dfx does is make everything look blurry from the texture filtering while running worse because of the added strain on the CPU from the 3dfx emulation.

**Comment by mkm007** [comment]
> Glad you got it working!
> 
> Both Blood and Shadow Warrior have problems with 3dfx but it's probably not because of DOSBox-Pure. Blood only ever received an alpha patch for 3dfx support, which is buggy and hard to get working, and Shadow Warrior can just show a black screen. It's like this on real hardware. You're not missing anything though... Build engine games look worse with 3dfx and they're still not true 3D, so all 3dfx does is make everything look blurry from the texture filtering while running worse because of the added strain on the CPU from the 3dfx emulation.

thank you for let me know and  tomb raider on 3dfx works perfectly....

**Comment by mkm007** [comment]
thanls
