### ISSUE TITLE
DOSBox Pure 0.9.7 is slower than old version (like 0.21)

### ISSUE THREAD

**Issue by schmurtzm** [schellingb/dosbox-pure#363]
Hi, on low CPU device like the Miyoo Mini (1.2ghz dual core processor, 128MB of RAM) dosbox-pure is significantly slower than before.
The comparison is done between v0.21 and v0.9.7.
Some users assume that is because the emulation becomes more accurate... but what the author of the core think about that ? 😉 

The decrease of performance is really noticeable with something like 50 to 75% of the performances of the old core.
That's a shame because the new features and fixes are really great.  A way to have the best of both worlds?

Here an issue about this subject on the Onion's repo (a Retroarch OS for the Miyoo Mini) :
https://github.com/OnionUI/Onion/issues/611

Thank you.

**Comment by schellingb** [comment]
Hi. I usually use the Quake timedemo benchmark to test CPU performance and at least on my Windows desktop 0.9.7 is 5% faster compared to 0.21. I just tried the entire evening to get RetroArch to run on my Raspberry Pi 4 (32 bit ARM) again but somehow was not successful. I ended up using the next best similar device I have which is my phone (quad core ARM64) and it showed similar improvements with 0.9.7 being 6% faster than 0.21. This is with all core options set to their defaults.

When incorporating improvements to get better Windows 95/98 compatibility I was very selective not to impact performance negatively. Changes that could affect performance I usually put behind having the setting `CPU Type` set to `Pentium (slow)`. If this setting is set to the default (`Auto`), regular DOS games should be as fast as ever and booting into an installed operating system (like Win 9x) will set the mode to Pentium to get the maximum compatibility.

Do you know where the builds for Miyoo Mini are coming from? Is there perhaps a chance that since 0.21 some settings have changed? Wrong compilation optimizations or missing activation of any math enhancements (like ARM NEON) can lead to large performance drops.

**Comment by schmurtzm** [comment]
Thanks for this feedback, tests and advice :) 
Indeed my compilation was not good, you hit the nail on the head ! 
Not sure if it is perfect for the Miyoo Mini but 
`make -f Makefile platform=unix-armv7-hardfloat-neon -j2`
gives better results a lot better than my previous build !
Really happy that the slowdown were not due to better accuracy and to see that the recent improvements are still compatible with low CPU device !
