### ISSUE TITLE
Request: Better Win3 support?

### ISSUE THREAD

**Issue by aorin1** [schellingb/dosbox-pure#421]
I've been using Pure for a few years now and it works great, the best DOS experience I've had and so easy to use.
I'm wondering if it's possible that pure could work with the Win3x0 pack from EXo somehow? Is it possible?

**Comment by schellingb** [comment]
Can you formulate your request more technical? What kind of features are you missing?

**Comment by aorin1** [comment]
> Can you formulate your request more technical? What kind of features are you missing?

Currently, when we try an ExoWin3x0 game, and try to load it with Pure, it will show the folders from C: and D: as it tends to do with normal DOS games, as shown in the screenshot:

https://ibb.co/HNzNqbM
The Exo pack comes with the games zipped with a folder instead of all files in the root, and instead of C:Windows, we get a C:SIMC23X\, when trying to load it, the core will say it requires windows to run.

I'm sure I'm missing something here but my doubt is more like, how, if possible, can we run Win3x0 games as we do with the normal DOS games?

**Comment by schellingb** [comment]
If you don't have WINDOWS in the ZIP file you are loading, then you won't have Windows, yes.

For bootable operating systems. like Windows 95 and 98, in DOSBox Pure since version 0.9.5 we have the `[ Boot and Install New Operating System ]` feature which installs an OS into a file that sits in the "System" directory of RetroArch.

I always thought it would be nice to have something similar for earlier, DOS based, Windows versions like Win3. I imagine you would have a ZIP file with just the WINDOWS directory inside System and then can load a ZIP with just the game. DOSBox Pure would then load both ZIPs, merge their structures into a single C: drive.

The only thing I'm stuck on is how to link up those two ZIPs. I guess, similar to the submenu available with `[ Run Installed Operating System ]` there would be another submenu `[ Run System Shell ]` (or something like that) and it would list up some specially named or specially marked ZIP files found in RetroArch's "System" directory. It is a bit lower priority than Windows 95/98 because you can just add Win3 to your games' ZIP file. But it would be nice to remove the need to do that if you have many Win3/2/1 games.

**Comment by aorin1** [comment]
> If you don't have WINDOWS in the ZIP file you are loading, then you won't have Windows, yes.
> 
> For bootable operating systems. like Windows 95 and 98, in DOSBox Pure since version 0.9.5 we have the `[ Boot and Install New Operating System ]` feature which installs an OS into a file that sits in the "System" directory of RetroArch.
> 
> I always thought it would be nice to have something similar for earlier, DOS based, Windows versions like Win3. I imagine you would have a ZIP file with just the WINDOWS directory inside System and then can load a ZIP with just the game. DOSBox Pure would then load both ZIPs, merge their structures into a single C: drive.
> 
> The only thing I'm stuck on is how to link up those two ZIPs. I guess, similar to the submenu available with `[ Run Installed Operating System ]` there would be another submenu `[ Run System Shell ]` (or something like that) and it would list up some specially named or specially marked ZIP files found in RetroArch's "System" directory. It is a bit lower priority than Windows 95/98 because you can just add Win3 to your games' ZIP file. But it would be nice to remove the need to do that if you have many Win3/2/1 games.

The Win 95/98 approaches are really interesting.
Yes, you explained it clearly enough so that I could understand how it works, at least the gist of it. While a few games are easy enough to fix manually, this request is mostly for frontend usage, specially since Pure provides a great "couch" experience and the amazing auto controller profiles, a bigger Win3x0 library would benefit a lot from what you suggest as a possible solution at the end of your last message. I understand that it would be similar to the 95/98 approach as it requires the base of Win3 to be present in the System directory.

**Comment by schellingb** [comment]
How would you expect to set this up though?

Would you read a document that tells you that you need to find a Windows 3 (or 3.1 or 3.11) installation and put it into a specially named .ZIP files inside RetroArch's 'System directory'?

Or alternatively, would you find a set of Windows 3 installation floppy disk images, mount the first one and have the start menu present you with an option `[ Install System Shell ]` which then runs you through the real Windows 3 installation to create that special file inside the System directory? That would be very similar to the `[ Boot and Install New Operating System ]` option we already have and would eliminate the need for much documentation. Just say "Load a real Windows installation disk set and go".

Obviously the second option is a bit more complex to implement but I feel like not many people read the documentation of a libretro core. And why would they... things really should "just work".

**Comment by aorin1** [comment]
I think the System zip approach is the simplest solution. Do you think it's easy to implement?

**Comment by schellingb** [comment]
Hmm, I'm just wondering what is it worth if no one will be able to use it (unless they read the documentation which basically no one does).

There still are some questions like what would the identifying key for such a ZIP file be. We can't just list any ZIP file in the System directory. So either it's every .DOSZ file, or every file named DOSBoxSystemShell*.zip.  Or every file in a specific subdirectory.

Another would be changes made to the C:\WINDOWS directory while running a game. The changes will probably end up in the save game of the game, they wouldn't modify the prepared System zip. But someone might expect that, but that would be rather complex. Having modifications apply per-game would be useful though, could set the game to autostart or something and it won't affect other games.

Other than that... maybe not. We could also go for a 2 step implementation. Support loading of a specially named System zip first, and then later add a way to make this  System zip inside DOSBox by mounting Windows 3 installation disks.

**Comment by aorin1** [comment]
That's true, this is not too simple.
In any case, you're the one to choose the best option, and if you decide it, let me know how I can help.

**Comment by i30817** [comment]
I implemented my own bootleg autoboot windows 3.11 and 95 game version a few years ago, although I did some weird weird things for it, and it only worked in Linux.

I had my games in a squashfs file, compressed. I also had 3 windows, 2 windows 3.11 at different resolutions and a windows 95 hd image.

I took special care that the windows 95 image was installed in a (dosbox made), hdd raw FAT16 file, so I could boot it of course. That windows when I installed it, I created a startup file that would invocate a fixed name startup file in 'd'

I had a copy-on-write overlay on the squashfs of course, but since I didn't want to save modifications to the OS, whenever I started a windows game I mounted the Linux path /dev/shm (memory mapping) as a drive, mounted the os dir as another, copied over the os dir or file, unmounted both and mounted (raw if hdd) the game and OS. The game was installed to the d drive obviously.

On windows 3.11 I just started the shell with the game executable or bat as argument, and on windows 95, I just booted it (the autostart would boot).

For some reason, this startup method crashed diablo 1 (something something explorer copy protection). But it worked with a lot of windows 95 games, and I didn't have to care about scandisk errors with the OS (with the games, yes, since copy on write).

That got tiresome. If I was going to try again, I might try windows 95 with pagefile disabled or with 'always delete modifications and depend on savestates' for the , although I'm not sure if either would save data correctly without the original game harddisk.

Games that tried to change the os to introduce drivers or QuickTime were the bane of this setup, and I eventually needed up with a quite altered os image to appease all the games anyway.

**Comment by i30817** [comment]
Ah well. I had a original point that got a bit obscured. It is 'if you install your own games, they don't need to be on c, and therefore you can separate them without the emulator merging zips for you'.

I can understand why you'd want a solution that doesn't require users to reinstall games though. Sounds like a extension of the overlay filesystem already in dosbox to support more than one level.

**Comment by schellingb** [comment]
Again, the 3 layers with a system shell is the following:
- Shared system shell ZIP (read only)
- Game ZIP (read only)
- Save ZIP (read & write)

So once Windows 3.11 is started, a shortcut to the game can be put into the StartUp group. The StartUp group (C:\WINDOWS\STARTUP.GRP) is then saved into the Save ZIP. If desired, the file can be moved from the Save ZIP into the Game ZIP.
Then, the shared system shell (i.e. Windows 3.11) can be marked as auto start in the DOSBox Pure start menu, it can be set with a "Skip Showing First X Frames". So with this, the entire startup of Windows 3 and the game will be fully skipped. The very first frame shown after selecting the game content in RetroArch will be the launched game. Windows 3 will not even be visible (if the game runs full screen).

Again not related to this issue, but automatic gamepad mapping doesn't rely on the existence of DOS4GW. A game is detected by seeing a game unique file (by checking the file name and file size). It often is not the game EXE file because there can be various patch versions of a game out there. Some games have multiple game-identifier files in the database.

Gamepad configuration and mapping has changed a lot since the last release. Please wait just a tiny bit more for the next update (unless you run your own builds from source). The [README](..#gamepad-mapper) has a preview :-) Although selecting a preset from a game with a (huge) list is not in there but maybe that can be added.

**Comment by schellingb** [comment]
The search already is rather fuzzy. For example Duke Nukem 3D is recognized by the existence of a 188954 byte sized "DUKE.RTS", Jazz Jackrabbit is recognized by "SOUNDS.000" with 130603 bytes or Jetpack is recognized by either "JETPACK3.DAT" with 38840 bytes, "LEVEL01.DAT" with 506 bytes or "SCLM.DAT" with 54508 bytes.
Having a means for users to contribute entries to the database (both identification and actual mapping) was always planned, maybe some day :-)

**Comment by toniosj** [comment]
I'm trying a Win3x game, Allied General, in 0.9.7 and I have this error:

![Win3x error](https://github.com/schellingb/dosbox-pure/assets/20826760/62fde314-8f21-403a-8837-f8f52e3815ad)

**Comment by schellingb** [comment]
This has been fixed by a8c3d70 which will be in the next release.
Currently github is blocking me from accessing my repository but as soon as that ends I plan to make a new release.

**Comment by toniosj** [comment]
Great @schellingb !!!

I'm so excited for this new version, the wait will surely have been worth it.

**Comment by i30817** [comment]
Btw I also had the startup group idea, but it doesn't apply to windows 95 hd images, which are opaque and not stackable (well I was intrigued by the qcow format, but nothing indicates dosbox would ever support it or its patch ability). So I ended using the 'startup group pointing to a bat file in d, pointing to the real game' in windows 95 images.

Can dosbox-pure stack windows 95 he's? Or rather, can dosbox-pure boot windows 95 games and os in zip files without killing the disk or memory by requiring the unzip of the whole thing into a new bootable image?

**Comment by schellingb** [comment]
A read-only OS image could theoretically be loaded from a IMG inside a ZIP, but there is no support for it for now. Because the default setting for the core option `System > Advanced > OS Disk Modifications` is to keep changes, it relies to being able to write them back to the IMG. Maybe we can scan for .IMZ files (compressed IMG files) and use them as read-only OS images.

Now in 0.9.8 there is the option to keep per game differencing disk for installed OS ([documentation](../#installing-an-operating-system)) (issue #423) which allows you to customize the OS per game. But keep in mind once you start using this option, you can never modify the base OS image again or any created per-content differences would not be usable anymore.

**Comment by schellingb** [comment]
@aorin1 I'm closing this issue now as the feature has been implemented as part of 0.9.8:
- Shared system shells (use one Windows 1/2/3 installation ZIP for multiple games) ([documentation](../#shared-system-shells-like-windows-3))

If there's any issues with the feature or something related, we can re-open the issue or just create a new one. Thanks for the request.
