### ISSUE TITLE
0.9.8 is not available on RetroArch

### ISSUE THREAD

**Issue by PoloniumRain** [schellingb/dosbox-pure#441]
By going to `Main Menu > Online Updater > Update Installed Cores` within RetroArch it will still download the previous 0.9.7 version. I'm guessing this isn't intentional?

Excellent work on this release BTW! Worth the wait. I haven't had time to test much yet, but with the first game i tried, Pro Binball, i've already found that the new option for increasing SVGA memory beyond 2MB allows for higher resolutions, more colours and faster loading times with this game :) Love the new Start Menu and colour scheme as well.

**Comment by schellingb** [comment]
Because it's such a big update (so long in the making...) I am taking things step-by-step this time. So I put the new release up only on the main source repository at first. I did push it to the libretro buildbot yesterday and at least for me this is now available in the online updater of RetroArch.

**Comment by PoloniumRain** [comment]
Ah right, that makes sense. I now see it on RA.
