### ISSUE TITLE
[Feature request] Page up/down list controller mapping list with left/right

### ISSUE THREAD

**Issue by InterClaw** [schellingb/dosbox-pure#453]
In the Gamepad Mapper, when selecting a mapping for a key, it would be nice to be able to press left/right on the keyboard or D-pad to "page" up and down (10 steps actually) like in the RetroArch menus when doing the same. Especially for the "Keyboard" option where there are a lot of selections to choose from the scrolling by holding down up/down gets a bit tiring. 😉

**Comment by PoloniumRain** [comment]
This feature is already there, but since 0.9.8 it now uses up/down on the controllers right analog stick. You can also hold the stick in either direction and it will page up/down quickly. Previous versions used the L1 and R1 shoulder buttons to page up/down. I think using up and down on the stick feels more natural than pressing left or right on the D-pad.

**Comment by InterClaw** [comment]
Nice, thanks for pointing that out. 👍

**Comment by schellingb** [comment]
Yes, for context we use D-Pad left/right for functions in the menu: 
- It sets the auto start frame skip amount in the Start Menu
- It switches controller ports in the Gamepad Mapper

And now since 0.9.8 L/R is used to switch "tabs" in the menu, between [START MENU] <-> [ON-SCREEN KEYBOARD] <-> [GAMEPAD MAPPER]. L2/R2 always was used to increase/decrease the cursor speed in the On-Screen Keyboard. So we're left with the right analog stick.
