### ISSUE TITLE
Unable to open CHD files with v0.9.9

### ISSUE THREAD

**Issue by trotsky40** [schellingb/dosbox-pure#464]
I am unable to open CHD files with the latest nightly of RetroArch and the 0.9.9 version of the core. 

These errors appear in the log:
[libretro INFO] [DOSBOX LOG] Invalid or sunsupported CHD file, must be an uncompressed version 5 CD image
[ERROR] [Environ]: SET_MESSAGE_EXT: Unable to open CD-ROM image file: C:\RetroArch\games\DOS\Star Wars - Rebel Assault (USA, Europe) (v1.7).chd

I have verfied that the CHD is version 5 and it is not stored in a Zip file (i.e. further compressed). 
![Screenshot 2024-01-19 08 45 09](https://github.com/schellingb/dosbox-pure/assets/25250513/fbac7095-722f-4b92-9e8e-303a84d6f257)

Are there specific settings needed when creating CHD files to make them compatible of DOSBox Pure?

**Comment by schellingb** [comment]
The release notes for [0.9.8 and 0.9.9](../releases/tag/0.9.9) said:
- Add support for uncompressed CHD version 5 CD images

Your CHD is compressed so it won't work. You can create uncompressed CHD files with `chdman.exe createcd -c none`.

I'll close this issue now because if there is any further development on this feature to extend support for the complex compression schemes of CHD it will be mentioned in the original issue for CHD support which is #40.
