### ISSUE TITLE
HD Images doesn't show up

### ISSUE THREAD

**Issue by reignerdeustcher** [schellingb/dosbox-pure#495]
I've created an hd image for the game **Enemy Infestation** in the system folder of retroarch for run with my installed windows 98 but the image doesn't appear to select in the list with the others.

You can see in the screen all the other images that i've created previously for other games but now it doesn't work anymore, at the bottom says: ''to refresh: Audio options/Midi output/Scan system directory'' but this doesn't make any sense...

![Enemy Infestation-240425-191023](https://github.com/schellingb/dosbox-pure/assets/79814905/4bb72a28-15c9-4b51-8849-381ba0456482)

**Comment by schellingb** [comment]
Normally DOSBox Pure checks the system folder on every startup (for sound fonts and OS images). But if the reading of that system folder takes a long time, it will instead save a index file called "DOSBoxPureMidiCache.txt" into the system folder. Once the index file exists it will no longer scan the entire folder but instead use the file. And to rebuild the index you need to initiate a refresh with the "Scan system directory" setting. It was originally only used for soundfonts so that's why it is under the "Audio Options".

It probably would be better if there was a "Refresh" option in the list of operating system disk images. I'll see if that can be added.

**Comment by reignerdeustcher** [comment]
> Normally DOSBox Pure checks the system folder on every startup (for sound fonts and OS images). But if the reading of that system folder takes a long time, it will instead save a index file called "DOSBoxPureMidiCache.txt" into the system folder. Once the index file exists it will no longer scan the entire folder but instead use the file. And to rebuild the index you need to initiate a refresh with the "Scan system directory" setting. It was originally only used for soundfonts so that's why it is under the "Audio Options".
> 
> It probably would be better if there was a "Refresh" option in the list of operating system disk images. I'll see if that can be added.

oh, even i checked the audio options before i didn't saw that option until now, it worked, thanks

**Comment by schellingb** [comment]
The newest version [1.0-preview1](../releases/tag/1.0-preview1) available here and from the RetroArch online core downloader now shows a 'Refresh List' option right in the list of bootable operating systems if it's needed. So it can't be as easily missed anymore, therefore I'm closing this issue.
