### ISSUE TITLE
Android 3dfx

### ISSUE THREAD

**Issue by fredgfgr** [schellingb/dosbox-pure#529]
I can build windows version (very easy for a noob like me) but is it possible to build an android version with the 3dfx hardware opengl ?

**Comment by schellingb** [comment]
You can try to get the Android NDK which shouldn't need to be installed, just unzipped. I use a fairly old version r20b available at https://github.com/android/ndk/wiki/Unsupported-Downloads but it should work with newer versions. Once you have the NDK, you should be able to open a command prompt and enter these commands
```sh
cd <DOSBOX-PURE-GIT-COPY-DIR>\jni
<ANDROID-NDK-DIR>\ndk-build.cmd -j4
copy /Y ..\libs\arm64-v8a\libretro.so dosbox_pure_libretro_android.so.20290101T0000000001.0000000001.0.lcbk
```
This should give you a file "dosbox_pure_libretro_android.so.20250101T0000000001.0000000001.0.lcbk" which you can put somewhere on your Android device (with an Arm64 processor), then open RetroArch on Android, go to "Load Core", then "Install or Restore a Core" then select that file to install your own build.
If you build again, I think you need to increase the "0000000001" to a higher number otherwise RetroArch thinks it is already installed.

If you can't get it to work, I can upload a build for Arm64 here.

**Comment by fredgfgr** [comment]
Thank you so much! I was able to compile a version for Android. Dosbox Pure is very impressive on PC and even more so on Android!!! You're doing an amazing job!!!

Here are the first tests I conducted:

 3dmark 99 software multithreaded
![3d_mark_softwareM](https://github.com/user-attachments/assets/2b2084b5-9066-41fd-b6bd-865dce36f1f7)
  3dmark 99 hardware 1x
![3d_mark_hardware_1X](https://github.com/user-attachments/assets/0b461397-7cb8-4079-b21e-fa23b7a63b93)
  3dmark 99 hardware 2x
![3d_mark_hardware_2X](https://github.com/user-attachments/assets/6a3ce27b-a2c2-451e-9468-7980ba1a882c)

**Comment by fredgfgr** [comment]
I have a XIAOMI  PAD 5 (Qualcomm Snapdragon 860), The only game I've tested so far is dark force II and it is now perfectly playable at 60fps with hardware x2
![Star Wars - Jedi Knight - Dark Forces 2-240825-090208](https://github.com/user-attachments/assets/796fe04c-98da-46a9-834d-a44b4ba650f5)

**Comment by fredgfgr** [comment]
Thank you very much for your help.
