### ISSUE TITLE
Sync with SVN

### ISSUE THREAD

**Issue by Torinde** [schellingb/dosbox-pure#530]
Last sync with upstream I see is https://github.com/schellingb/dosbox-pure/commit/2f9583f4421449a8a24fcde3cf1367e0e7cdff9a

- https://sourceforge.net/p/dosbox/code-0/4484/ Fix wav capture glitches on buffer wrap around

**Comment by schellingb** [comment]
This core has all the capture features of upstream DOSBox removed so that commit is irrelevant for us.

**Comment by schellingb** [comment]
No, I removed it because I think it has no place in a libretro core, where the frontend likely has capture features for video and audio. Similar to the debugger which is also removed. I think those are cool features for a development oriented emulator but we're trying to run games here :-)
 
What type of data do you want to capture from DOSBox that isn't covered by RetroArch?
