### ISSUE TITLE
Change folders to mount in root directory in C:\

### ISSUE THREAD

**Issue by toniosj** [schellingb/dosbox-pure#555]
I want to use the games from the eXoDos/eXoWin pack directly, but all the games have a parent folder, above the game folder (and the WINDOWS folder in the case of eXoWin).

Game.zip
-Parentfolder
--Folder Game
--Windows Folder (eXoWin Pack)

Dosbox mounts the drive
C:\parentfolder\foldergame
C:\parentfolder\Windows

My question is if there is a way to mount a folder or several folders as root directories C:, above the main one, so that the game and the windows folder are mounted in the root directory.

That is, skip the parentfolder.
C:\foldergame
C:\Windows

Is there a way to do this?

**Comment by alexb3d** [comment]
I'm a bit confused.

I assume you're placing the w95 vhd image in the System folder and loading the iso from the Load menu. As the documentation says?

Anyway, use these image formats with caution, they may give errors, DOSBox is not strictly speaking a virtual machine and it supports many tricks.

**Comment by yonailo** [comment]
Hello @alexb3d,

I have not followed the previous dicussions, but I find this PR interesting in order to ease the usage of those precompiled packages.  Adding an option like this would benefit end-users, which could just drop those compilations and start playing without any additional steps.

I’m not sure if the limitation is technical, a matter of project scope as you mentioned, or a preference not to support these kinds of compilations. I have asked ChatGPT how many options the bash command "find" has, and it has told me over "50".

I hope you will never end up with over 50 different command line options, but please consider something like this PR from the point of view of a user which downloads an entire colletion of well-structured DOS games and which would like to use your execellent software to play them.

**Comment by alexb3d** [comment]
Actually it was like that before, it mounted the folders, but it is not the natural way. Pure respects the original PC structure. 

The precompiled files are wonderful, but they are designed for another emulation system.

Configuring a game the way it was done in those days, is something that may be pleasing to some, it's nostalgic.

Still, it would be very interesting and convenient if you could load the precompiled ones (like eXo) 

Do you think it is possible to have something to ignore that first folder and load the content in C: ? 
@schellingb It can be an extension (like the one to load in drive) game.pre.zip or game.com.zip 
or... 
game.conf.zip and that at once activates the configuration to load the .conf

**Comment by yonailo** [comment]
It might be difficult to implement something like this, as a zip file could potentially have multiple directories and/or files at its root… on the other hand, if the zip file has one and only one single root directory (no other files, only a single directory), it could be automatically ignored and the mounted path could start inside it ….

**Comment by yonailo** [comment]
@toniosj can you give us a exodos’ title that could benefit from this feature ? It could help for testing purposes …

**Comment by toniosj** [comment]
> @toniosj can you give us an exodos’ title that could benefit from this feature ? It could help for testing purposes and to better understand the issue here.

An example: MDK

The game only works with C:\MDK\

But dosboxpure automounts exodos game as C:\MDK\MDK\

**Comment by schellingb** [comment]
> My question is if there is a way to mount a folder or several folders as root directories C:, above the main one, so that the game and the windows folder are mounted in the root directory.

@toniosj The core provides the "Shared System Shell" feature which lets you basically load 2 ZIP files as C:. Though not into separate folders, they just get overlaid directly. See the documentation about it here: ["Shared System Shell"](..#shared-system-shells-like-windows-3).

> @schellingb Do you think it is possible to have something to ignore that first folder and load the content in C:?

It's funny you suggest that. The core actually used to do that until c763ce0 which was released with 0.9.0. It caused all kinds of issues which you find documented in #87. Future versions of the core will offer the `SUBST` command, which was added as part of #479, which can then be used together with `REMOUNT` in a batch file if such a behavior were desired. But the real solution is to have ZIP files that match the desired file system structure. The given example wants to have `\MDK\MDK\` in the ZIP appear as `C:\MDK\` in DOS, but that would mean that a correct ZIP with just `\MDK\` would appear as `C:\`.

I'm not sure having a special extension like suggested makes much sense. It is much easier to just un-zip and re-zip. All desktop operating systems offer these functions so anyone can do it and it doesn't need a manual to explain some special file naming to work around issues with people's ZIP files.

Please try to keep discussion relevant to the first post of the issue. There are all kinds of very similar issues to this and to what is being discussed, it would be immensely useful if the discussions were kept in the same place and if overall open issues were kept low. DOS games that require to exist in a specific location and how that potentially could be automatically fixed by the core is what the issue #87 is about.

**Comment by toniosj** [comment]
@schellingb thanks!! It works with SUBST parameter! Now I can remount drive C as I want.

remount C Y
SUBST C: Y:\MDK

It works too for win3x eXo games.

Thanks for the info!

**Comment by alexb3d** [comment]
> It is much easier to just un-zip and re-zip.

this is the solution, without a doubt.

I didn't know there was a dedicated post, it's very good.

sorry for the confusion.
