### ISSUE TITLE
Maybe make GCC9 an ifdef?

### ISSUE THREAD

**Issue by parkerlreed** [schellingb/dosbox-pure#8]
I spent 20 minutes compiling gcc9 on AArch64 only for it to fail and then realized DOSBox-Pure works with GCC 10. 

Possibly just make GCC9 apply only if arch is armv7?

**Comment by schellingb** [comment]
If someone can guarantee that the codegen bug in GCC10 only affects armv7 then sure. I tried reaching out to gcc people but got ignored so this was the only solution I felt comfortable with while encountering the issue 2 days before release. Maybe I should have gone with clang :-)

**Comment by parkerlreed** [comment]
Thanks! 

From personal testing I can confirm that 10 works on both x86_64 and AArch64. Able to load in and play a game (assuming armv7's segfault is instant)

**Comment by schellingb** [comment]
armv7's segfault happens when the dynrec cpu kicks in, which is when a game using protected-mode is booting (often visible to the user through DOS4GW starting up). So the start menu, commandline and older games run fine.

Thanks for testing! I'll put the comment and g++-9 specific stuff into the arm7 if then 👍

**Comment by parkerlreed** [comment]
Just double checked with Duke Nukem 3D since I know that uses DOS4GW. Working well on both platforms.

**Comment by schellingb** [comment]
Fixed as of 603b1c7
