### ISSUE TITLE
Why not to fork dosbox-staging?

### ISSUE THREAD

**Issue by rtentser** [schellingb/dosbox-pure#9]
This [one](https://github.com/dosbox-staging/dosbox-staging/). Any reasons?

**Comment by schellingb** [comment]
That fork is over 8 MB and requires to ship with 15 DLLs.  
For comparison, DOSBox Pure is 2 MB.

Personally I like to keep things small, manageable, have close to zero (or actually zero in the case of this project) external library dependencies to keep things simple. I know in the age of web developers that love to use npm which pulls in hundreds and hundreds of external dependencies this is almost outrageous. But hey, I'm not going there.

If original DOSBox were such a dependency spiderweb I wouldn't even have started this project. It only exists because DOSBox SVN is easy to compile, simple, manageable.

Hope that explains my reasoning.

If you're curious and want to see more examples of my philosophy, feel free to check out http://zillalib.github.io/games/ - The games there load quicker than most websites these days. Small, fast, good code that can reasonably and entirely be overseen by a single human. They don't teach that at coding school anymore I think :-)

**Comment by rtentser** [comment]
> Hope that explains my reasoning.

Yes, it does. Thank you!

**Comment by dreamer** [comment]
> That fork is over 8 MB and requires to ship with 15 DLLs.

No, it does not require them. Our Windows release builds ship with these because of features that users want. You configure the dependencies you want during compilation time, e.g.:

- `./configure --disable-network` -> no SDL_net dependency (and no serialmodem emulation nor IPX over UDP)
- `./configure --disable-opus-cdda` -> no Opusfile dependency (and no support for Opus in .cue files)
- `./configure --disable-screenshots` -> no libpng dependency, no zlib dependency (and disabled support for built-in screenshots functionality)
- `./configure --disable-fludsynth` -> no FluidSynth and libraries required by that library (and no build-in MIDI synth)
- `./configure --disable-opengl` -> no OpenGL (and no output=opengl nor built-in shaders)
