### ISSUE TITLE
Turrican 2 and Flash Back games crashes.

### ISSUE THREAD

**Issue by atticus81** [schellingb/dosbox-pure#93]
Greetings.

Turrican 2 have issues when starts the game with the config setup mode.

Flash Back  crashes when open dosbox keyboard overlay.

Thanks.

**Comment by schellingb** [comment]
Thank you for reporting the crash in Flashback, that game runs in the resolution 256x224 which was too low for the on-screen keyboard. The crash will be fixed in the next release.

In regards to Turrican 2, can you try some of the recommendations on these sites?
https://www.dosbox.com/comp_list.php?showID=1937
https://www.vogons.org/viewtopic.php?t=53295
It seems a bit finicky in regards to various file locations. It should work when the required files are all in place.
The "Video Settings" option in the configuration screen does not work in regular DOSBox as well as in DOSBox Pure, but it should not be required.

**Comment by schellingb** [comment]
@atticus81 The on-screen keyboard in Flashback should be fixed in [the latest release](../releases/latest), if you have some time, please check it out.
